command:
  - python
  - scripts/run_constructor.py
  - --model_name_or_path
  - deepvk/bert-base-uncased
  - --train_file
  - data/train/mnli/train.csv
  - --validation_file 
  - "data/validation/mnli/dev.csv"
  - --test_files 
  - "mnli:data/validation/mnli/dev.csv,
     ru_wanli:data/validation/ru_wanli/test.csv,
     terra:data/validation/terra/val.csv,
     rumednli:data/validation/rumednli/test.csv,
     fever_translated:data/validation/fever_translated/train.csv,
     ling_translated:data/validation/ling_translated/train.csv,
     rcb:data/validation/rcb/val.csv,
     wanli_translated:data/validation/wanli_translated/train.csv,
     xnli:data/validation/xnli/test.csv,
     anli:data/validation/anli/dev.csv,
     snli:data/validation/snli/dev.csv"
  - --metric_name 
  - f1
  - --text_column_delimiter 
  - " "
  - --do_train 
  - True
  - --do_eval 
  - True
  - --max_seq_length 
  - 512
  - --logging_strategy 
  - steps
  - --evaluation_strategy 
  - steps
  - --save_strategy 
  - steps
  - --logging_first_step
  - True
  - --save_total_limit 
  - 3
  - --metric_for_best_model 
  - f1
  - --output_dir 
  - tmp/mnli
  - --num_train_epochs
  - 5
  - --load_best_model_at_end
  - True
  - --per_device_train_batch_size
  - 8
  - --learning_rate
  - 5e-6
  - --dropout_rate
  - 0.1
  - --adam_beta1
  - 0.999
  - --warmup_steps
  - 15000
  - ${args}
method: grid
parameters:
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]